apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sor
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: "app-image"
    newName: "ghcr.io/andreaschristianson/space-of-resolution:latest"
    newTag: "initial"
